### ISSUE TITLE
Problem in installing

### ISSUE THREAD

**Issue by purplelily98** [wilddom/memrise2anki-extension#55]
Hi, I am new to this but I have tried this following the instructions to the letter but I could not install it. 
I click Tools > Add-ons > From GitHub and paste the path, and click OK. It pauses for a while and it will return as before with no change. I do not see the add-on available in Tools. Did I do something wrong or did I miss something?

Thanks!

**Comment by wilddom** [comment]
I like the idea of [AnkiHub](https://github.com/dayjaby/AnkiHub) because it notifies you when there is a new update of an addon available. But unfortunately it doesn't seem to work very reliably at the moment. So it's actually an issue of [AnkiHub](https://github.com/dayjaby/AnkiHub) which you could report to the author. But you can always try to install the memrise extension manually.
