### ISSUE TITLE
Installation code is missing

### ISSUE THREAD

**Issue by kandyman2017** [wilddom/memrise2anki-extension#99]
On the installation page, where it is supposed to say the Add On code, it just says "deleted".

**Comment by wilddom** [comment]
That's because I don't like the AnkiWeb addon catalog. IMHO it's badly managed, there are a lot of duplicated addons and the review system is very often misused for nonsensical bug reports which read like "doesn't work - thumbs down". Therefore I deleted the addon from the catalog, those you can find there were not uploaded by me.
